### ISSUE TITLE
Fail to download the RhoFold checkpoint

### ISSUE THREAD

**Issue by zaixizhang** [rish-16/rna-backbone-design#1]
Hi, 

Thanks for your brilliant work! I tried to download the RhoFold checkpoint for evaluation: wget https://proj.cse.cuhk.edu.hk/aihlab/RhoFold/api/download?filename=RhoFold_pretrained.pt -O RhoFold_pretrained.pt

However, it fails to download the checkpoint. Could you provide some suggestions? Thanks!

**Comment by rish-16** [comment]
Hello,

Thank you for checking out our project! Sorry for the delay in getting back to you – GitHub doesn't send notifications properly 😅 

We've pushed our checkpoints and miscellaneous files into a Google Drive for easier access. You can download them here:

> [https://drive.google.com/drive/folders/1umg0hgkBl7zsF_2GdCIKkfsRWbJNEOvp?usp=sharing](https://drive.google.com/drive/folders/1umg0hgkBl7zsF_2GdCIKkfsRWbJNEOvp?usp=sharing)

Hope this helps, happy to clarify anything else!

Cheers,
R
